language: node_js
node_js:
  - "6"
  - "5"
  - "4"

addons: 
  code_climate: 
    repo_token: c913ce5cbb0ff01bdfef06f9b7dedfbd779b8a8d92352000637565f2c4367c44

before_script:
  - npm install

script:
  - gulp test
  - gulp build
  - gulp package

after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

