language: node_js
node_js:
  - "6"
  - "5"
  - "4"

before_script:
  - npm install

script:
  - gulp test
  - gulp build
  - gulp package

after_success:
  - codeclimate-test-reporter < coverage/lcov.info

dist: trusty

